"""Rich terminal renderer and Markdown exporter."""
from __future__ import annotations
from collections import Counter
from datetime import datetime

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.text import Text
from rich import box

from .parser import CommitRecord, COMMIT_TYPES
from .hotspots import Hotspot


def _type_counts(commits: list[CommitRecord]) -> Counter:
    return Counter(c.commit_type for c in commits)


def _bar(count: int, max_count: int, width: int = 20) -> str:
    filled = int((count / max_count) * width) if max_count else 0
    return "\u2588" * filled + "\u2591" * (width - filled)


def render_terminal(
    commits: list[CommitRecord],
    hotspots: list[Hotspot],
    heatmap: dict,
    since: datetime,
) -> None:
    console = Console()
    since_str = since.strftime("%Y-%m-%d %H:%M UTC")
    console.print()
    console.print(Panel(
        f"[bold cyan]deltabrief[/] \u2014 [dim]{len(commits)} commits since {since_str}[/]",
        box=box.DOUBLE_EDGE,
        style="bold",
    ))

    # Commit type breakdown
    type_counts = _type_counts(commits)
    max_count = max(type_counts.values()) if type_counts else 1
    table = Table(title="Commit Breakdown", box=box.SIMPLE_HEAD)
    table.add_column("Type", style="bold")
    table.add_column("Count", justify="right", style="cyan")
    table.add_column("Distribution")
    for ctype, label in COMMIT_TYPES.items():
        count = type_counts.get(ctype, 0)
        if count == 0:
            continue
        bar = _bar(count, max_count)
        table.add_row(label, str(count), f"[green]{bar}[/]")
    console.print(table)

    # Breaking changes
    breaking = [c for c in commits if c.breaking]
    if breaking:
        console.print(Panel(
            "\n".join(f"[red]\u26a0[/]  [bold]{c.short_sha}[/] {c.description}" for c in breaking),
            title="[red]Breaking Changes[/]",
            border_style="red",
        ))

    # Hotspot files
    if hotspots:
        ht = Table(title="Hotspot Files", box=box.SIMPLE_HEAD)
        ht.add_column("File", style="yellow", no_wrap=True)
        ht.add_column("Changes", justify="right", style="cyan")
        ht.add_column("Top Type", style="dim")
        for h in hotspots:
            top_type = max(h.commit_types, key=h.commit_types.get) if h.commit_types else "other"
            ht.add_row(h.path, str(h.change_count), COMMIT_TYPES.get(top_type, top_type))
        console.print(ht)

    # Author heat map
    at = Table(title="Author Activity", box=box.SIMPLE_HEAD)
    at.add_column("Author", style="magenta")
    at.add_column("Commits", justify="right", style="cyan")
    at.add_column("+lines", justify="right", style="green")
    at.add_column("-lines", justify="right", style="red")
    for author, data in sorted(heatmap.items(), key=lambda x: -x[1]["count"]):
        at.add_row(
            author,
            str(data["count"]),
            f"+{data['insertions']}",
            f"-{data['deletions']}",
        )
    console.print(at)

    # Recent commits
    rt = Table(title="Recent Commits", box=box.SIMPLE_HEAD)
    rt.add_column("SHA", style="dim")
    rt.add_column("Type", style="bold")
    rt.add_column("Description")
    rt.add_column("Author", style="magenta")
    rt.add_column("When", style="dim")
    for c in commits[:20]:
        label = COMMIT_TYPES.get(c.commit_type, "\U0001f4e6 Other")
        rt.add_row(
            c.short_sha,
            label,
            c.description[:60],
            c.author,
            c.timestamp.strftime("%m-%d %H:%M"),
        )
    console.print(rt)
    console.print()


def render_markdown(
    commits: list[CommitRecord],
    hotspots: list[Hotspot],
    heatmap: dict,
    since: datetime,
) -> str:
    since_str = since.strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        f"# deltabrief \u2014 Git Briefing",
        f"",
        f"> Generated by [deltabrief](https://github.com/DucChau/deltabrief) \u00b7 {len(commits)} commits since {since_str}",
        f"",
        f"## Commit Breakdown",
        f"",
    ]
    type_counts = _type_counts(commits)
    for ctype, label in COMMIT_TYPES.items():
        count = type_counts.get(ctype, 0)
        if count:
            lines.append(f"- {label}: **{count}**")
    lines += ["", "## Hotspot Files", ""]
    if hotspots:
        lines.append("| File | Changes |")
        lines.append("|------|---------|")
        for h in hotspots:
            lines.append(f"| `{h.path}` | {h.change_count} |")
    else:
        lines.append("_No file data available._")
    lines += ["", "## Author Activity", ""]
    lines.append("| Author | Commits | +lines | -lines |")
    lines.append("|--------|---------|--------|--------|")
    for author, data in sorted(heatmap.items(), key=lambda x: -x[1]["count"]):
        lines.append(f"| {author} | {data['count']} | +{data['insertions']} | -{data['deletions']} |")
    lines += ["", "## Recent Commits", ""]
    for c in commits[:30]:
        label = COMMIT_TYPES.get(c.commit_type, "\U0001f4e6 Other")
        lines.append(f"- `{c.short_sha}` {label} **{c.description[:70]}** \u2014 _{c.author}_")
    lines += ["", "---", "_Created by [hellohaven.ai](https://hellohaven.ai)_", ""]
    return "\n".join(lines)
